# Generated by Django 2.2.3 on 2019-08-12 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comic_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('make_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='images/')),
                ('post_date', models.DateTimeField()),
                ('rating', models.IntegerField(default=1)),
                ('votes_total', models.IntegerField(default=1)),
                ('comic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.Comic')),
                ('make_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.Make')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
