# Generated by Django 2.2.3 on 2019-08-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toys',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='toys',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
    ]
