# Generated by Django 2.2.3 on 2019-08-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20190813_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='make_name',
            new_name='makeName',
        ),
        migrations.RenameField(
            model_name='toys',
            old_name='make_name',
            new_name='makeName',
        ),
        migrations.AlterField(
            model_name='toys',
            name='makeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.Make', to_field='make_name'),
        ),
    ]
