# Generated by Django 2.2.3 on 2020-04-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_auto_20190827_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toys',
            name='comic_name',
        ),
        migrations.RemoveField(
            model_name='toys',
            name='rating',
        ),
        migrations.AlterField(
            model_name='toys',
            name='makeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.Make'),
        ),
        migrations.DeleteModel(
            name='Comic',
        ),
    ]
